version: '3'

services:
  client:
    build: ./services/client
    command: npm run dev
    environment:
      NODE_ENV: development
      PORT: 8080
    volumes:
      - ./services/client:/app
    ports:
      - 8080:8080
